name: FE CI/CD Pipeline
on:
  push:
    branches: [master]
    paths:
      - "client/**"
jobs:
  build-and-deploy:
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR Login
        uses: azure/docker-login@v2
        with:
          login-server: sunbud.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push FE
        run: |
          docker build \
            --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
            -t sunbud.azurecr.io/client:${{ github.sha }} ./client
          docker push sunbud.azurecr.io/client:${{ github.sha }}

      - name: Update Client Container
        run: |
          az containerapp up \
            --name sunbud-client \
            --image sunbud.azurecr.io/client:${{ github.sha }} \
            --ingress external \
            --location southeastasia \
            --registry-server sunbud.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --target-port 80 \
