name: Deployment
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR Login
        uses: azure/docker-login@v2
        with:
          login-server: sunbud.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push container
        run: |
          docker build \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -t sunbud.azurecr.io/sunbud:${{ github.sha }} .
          docker push sunbud.azurecr.io/sunbud:${{ github.sha }}

      - name: Update Container
        run: |
          az containerapp up \
            --name sunbud \
            --image sunbud.azurecr.io/sunbud:${{ github.sha }} \
            --ingress external \
            --environment sunbud-container-env \
            --location southeastasia \
            --registry-server sunbud.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --target-port 3000 \
